package new

const (
	CMD            = "cmd"
	API            = "api"
	BOOTSTRAP      = "bootstrap"
	ROUTER         = "router"
	MAIN           = "main"
	INTERNAL       = "internal"
	CONFIG         = "config"
	DI             = "di"
	HEALTH         = "health"
	INFRA          = "infra"
	MIGRATIONS     = "migrations"
	SQLC           = "sqlc"
	QUERIES        = "queries"
	WEB            = "web"
	BUILD          = "build"
	DEPLOYMENTS    = "deployments"
	LOCAL          = "local"
	STAGING        = "staging"
	DOCKER_COMPOSE = "docker-compose"
	SERVICE        = "service"
	REQUESTS       = "requests"
	RESPONSES      = "responses"
	HANDLER        = "handler"
	ERRORS         = "errors"
	TEST           = "test"
	GO             = "go"
	YAML           = "yaml"
	ENV            = ".env"
	GITIGNORE      = ".gitignore"
	README         = "README.md"
	DOCKERFILE     = "Dockerfile"
	AIR_TOML       = "air"
	TOML           = "toml"
)

const (
	TMPL_MAIN               = "main.go.tmpl"
	TMPL_BOOTSTRAP          = "bootstrap.go.tmpl"
	TMPL_ROUTER             = "router.go.tmpl"
	TMPL_HEALTH             = "health.go.tmpl"
	TMPL_CONFIG             = "config.go.tmpl"
	TMPL_DI                 = "di.go.tmpl"
	TMPL_ENV                = ".env.tmpl"
	TMPL_LOCAL_ENV          = "local.env.tmpl"
	TMPL_GITIGNORE          = ".gitignore.tmpl"
	TMPL_DOCKERFILE         = "Dockerfile.tmpl"
	TMPL_AIR_TOML           = "air.toml.tmpl"
	TMPL_SQLC               = "sqlc.yaml.tmpl"
	TMPL_DOCKER_COMPOSE     = "docker-compose.yaml.tmpl"
	TMPL_VPS_DOCKER_COMPOSE = "vps-docker-compose.yaml.tmpl"
)

const (
	DEFAULT_MOD_PATH = "github.com/nayefradwi"
	TESTIFY          = "github.com/stretchr/testify"
	CHI              = "github.com/go-chi/chi/v5"
	PGX              = "github.com/jackc/pgx/v5"
	REDIS            = "github.com/redis/go-redis/v9"
	GODOTENV         = "github.com/joho/godotenv"
	GRPC             = "google.golang.org/grpc"
	PGUTIL           = "github.com/nayefradwi/nayef_go_common/pgutil"
	AUTH             = "github.com/nayefradwi/nayef_go_common/auth"
	REDISUTIL        = "github.com/nayefradwi/nayef_go_common/redisutil"
	HTTPUTIL         = "github.com/nayefradwi/nayef_go_common/httputil"
	GRPCUTIL         = "github.com/nayefradwi/nayef_go_common/grpcutil"
	VALIDATION       = "github.com/nayefradwi/nayef_go_common/validation"
	PAGINATION       = "github.com/nayefradwi/nayef_go_common/pagination"
	OTP              = "github.com/nayefradwi/nayef_go_common/otp"
	LOCKING          = "github.com/nayefradwi/nayef_go_common/locking"
	COMMON_ERRORS    = "github.com/nayefradwi/nayef_go_common/errors"
	ERRORSPB         = "github.com/nayefradwi/nayef_go_common/errorspb"
)
