package new

const (
	CMD        = "cmd"
	API        = "api"
	BOOTSTRAP  = "bootstrap"
	ROUTER     = "router"
	MAIN       = "main"
	INTERNAL   = "internal"
	CONFIG     = "config"
	DI         = "di"
	HEALTH     = "health"
	INFRA      = "infra"
	MIGRATIONS = "migrations"
	SQLC       = "sqlc"
	QUERIES    = "queries"
	WEB            = "web"
	BUILD          = "build"
	DEPLOYMENTS    = "deployments"
	LOCAL          = "local"
	DOCKER_COMPOSE = "docker-compose"
	SERVICE    = "service"
	REQUESTS   = "requests"
	RESPONSES  = "responses"
	HANDLER    = "handler"
	ERRORS     = "errors"
	TEST       = "test"
	GO         = "go"
	YAML       = "yaml"
	ENV        = ".env"
	GITIGNORE  = ".gitignore"
	README     = "README.md"
	DOCKERFILE = "Dockerfile"
	AIR_TOML   = "air"
	TOML       = "toml"
)

const (
	DEFAULT_MOD_PATH = "github.com/nayefradwi"
	TESTIFY          = "github.com/stretchr/testify"
	CHI              = "github.com/go-chi/chi/v5"
	PGX              = "github.com/jackc/pgx/v5"
	REDIS            = "github.com/redis/go-redis/v9"
	GODOTENV         = "github.com/joho/godotenv"
	GRPC             = "google.golang.org/grpc"
	PGUTIL           = "github.com/nayefradwi/nayef_go_common/pgutil"
	AUTH             = "github.com/nayefradwi/nayef_go_common/auth"
	REDISUTIL        = "github.com/nayefradwi/nayef_go_common/redisutil"
	HTTPUTIL         = "github.com/nayefradwi/nayef_go_common/httputil"
	GRPCUTIL         = "github.com/nayefradwi/nayef_go_common/grpcutil"
	VALIDATION       = "github.com/nayefradwi/nayef_go_common/validation"
	PAGINATION       = "github.com/nayefradwi/nayef_go_common/pagination"
	OTP              = "github.com/nayefradwi/nayef_go_common/otp"
	LOCKING          = "github.com/nayefradwi/nayef_go_common/locking"
	COMMON_ERRORS    = "github.com/nayefradwi/nayef_go_common/errors"
	ERRORSPB         = "github.com/nayefradwi/nayef_go_common/errorspb"
)
