// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/errorspb/v1/errors.proto

package errorspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetailsPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetailsPb) Reset() {
	*x = ErrorDetailsPb{}
	mi := &file_proto_errorspb_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetailsPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailsPb) ProtoMessage() {}

func (x *ErrorDetailsPb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_errorspb_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailsPb.ProtoReflect.Descriptor instead.
func (*ErrorDetailsPb) Descriptor() ([]byte, []int) {
	return file_proto_errorspb_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetailsPb) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorDetailsPb) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorDetailsPb) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type ErrorDetailsPbList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ErrorDetailsPb      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetailsPbList) Reset() {
	*x = ErrorDetailsPbList{}
	mi := &file_proto_errorspb_v1_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetailsPbList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailsPbList) ProtoMessage() {}

func (x *ErrorDetailsPbList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_errorspb_v1_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailsPbList.ProtoReflect.Descriptor instead.
func (*ErrorDetailsPbList) Descriptor() ([]byte, []int) {
	return file_proto_errorspb_v1_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetailsPbList) GetItems() []*ErrorDetailsPb {
	if x != nil {
		return x.Items
	}
	return nil
}

type ResultErrorPb struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Message       string                         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                         `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Errors        map[string]*ErrorDetailsPbList `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultErrorPb) Reset() {
	*x = ResultErrorPb{}
	mi := &file_proto_errorspb_v1_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultErrorPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultErrorPb) ProtoMessage() {}

func (x *ResultErrorPb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_errorspb_v1_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultErrorPb.ProtoReflect.Descriptor instead.
func (*ResultErrorPb) Descriptor() ([]byte, []int) {
	return file_proto_errorspb_v1_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ResultErrorPb) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResultErrorPb) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ResultErrorPb) GetErrors() map[string]*ErrorDetailsPbList {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_proto_errorspb_v1_errors_proto protoreflect.FileDescriptor

const file_proto_errorspb_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/errorspb/v1/errors.proto\x12\x11proto.errorspb.v1\"T\n" +
	"\x0eErrorDetailsPb\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\"M\n" +
	"\x12ErrorDetailsPbList\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.proto.errorspb.v1.ErrorDetailsPbR\x05items\"\xe5\x01\n" +
	"\rResultErrorPb\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12D\n" +
	"\x06errors\x18\x03 \x03(\v2,.proto.errorspb.v1.ResultErrorPb.ErrorsEntryR\x06errors\x1a`\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.proto.errorspb.v1.ErrorDetailsPbListR\x05value:\x028\x01B\fZ\n" +
	".;errorspbb\x06proto3"

var (
	file_proto_errorspb_v1_errors_proto_rawDescOnce sync.Once
	file_proto_errorspb_v1_errors_proto_rawDescData []byte
)

func file_proto_errorspb_v1_errors_proto_rawDescGZIP() []byte {
	file_proto_errorspb_v1_errors_proto_rawDescOnce.Do(func() {
		file_proto_errorspb_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_errorspb_v1_errors_proto_rawDesc), len(file_proto_errorspb_v1_errors_proto_rawDesc)))
	})
	return file_proto_errorspb_v1_errors_proto_rawDescData
}

var file_proto_errorspb_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_errorspb_v1_errors_proto_goTypes = []any{
	(*ErrorDetailsPb)(nil),     // 0: proto.errorspb.v1.ErrorDetailsPb
	(*ErrorDetailsPbList)(nil), // 1: proto.errorspb.v1.ErrorDetailsPbList
	(*ResultErrorPb)(nil),      // 2: proto.errorspb.v1.ResultErrorPb
	nil,                        // 3: proto.errorspb.v1.ResultErrorPb.ErrorsEntry
}
var file_proto_errorspb_v1_errors_proto_depIdxs = []int32{
	0, // 0: proto.errorspb.v1.ErrorDetailsPbList.items:type_name -> proto.errorspb.v1.ErrorDetailsPb
	3, // 1: proto.errorspb.v1.ResultErrorPb.errors:type_name -> proto.errorspb.v1.ResultErrorPb.ErrorsEntry
	1, // 2: proto.errorspb.v1.ResultErrorPb.ErrorsEntry.value:type_name -> proto.errorspb.v1.ErrorDetailsPbList
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_errorspb_v1_errors_proto_init() }
func file_proto_errorspb_v1_errors_proto_init() {
	if File_proto_errorspb_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_errorspb_v1_errors_proto_rawDesc), len(file_proto_errorspb_v1_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_errorspb_v1_errors_proto_goTypes,
		DependencyIndexes: file_proto_errorspb_v1_errors_proto_depIdxs,
		MessageInfos:      file_proto_errorspb_v1_errors_proto_msgTypes,
	}.Build()
	File_proto_errorspb_v1_errors_proto = out.File
	file_proto_errorspb_v1_errors_proto_goTypes = nil
	file_proto_errorspb_v1_errors_proto_depIdxs = nil
}
