name: CI auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"
      - "!auth/authpg/**"
      - "!auth/authhttp/**"
      - "!auth/authconnect/**"
      - "!auth/authredis/**"
      - "!auth/examples/**"
  pull_request:
    paths:
      - "auth/**"
      - "!auth/authpg/**"
      - "!auth/authhttp/**"
      - "!auth/authconnect/**"
      - "!auth/authredis/**"
      - "!auth/examples/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci-go-module.yml
    with:
      module_path: auth
