name: CI connectutil

on:
  push:
    branches:
      - main
    paths:
      - "connectutil/**"
  pull_request:
    paths:
      - "connectutil/**"

jobs:
  ci:
    uses: ./.github/workflows/ci-go-module.yml
    with:
      module_path: connectutil
