name: CI httputil

on:
  push:
    branches:
      - main
    paths:
      - "httputil/**"
  pull_request:
    paths:
      - "httputil/**"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci-go-module.yml
    with:
      module_path: httputil
