name: CI validation

on:
  push:
    branches:
      - main
    paths:
      - "validation/**"
  pull_request:
    paths:
      - "validation/**"

jobs:
  ci:
    uses: ./.github/workflows/ci-go-module.yml
    with:
      module_path: validation
