name: Release authhttp

on:
  push:
    branches:
      - main
    paths:
      - "auth/authhttp/**"

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/deploy-go-module.yml
    with:
      module_path: auth/authhttp
      bump_type: major
    secrets: inherit
