name: Release auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"
      - ".github/workflows/release-auth.yml"
      - "!auth/authpg/**"
      - "!auth/authhttp/**"
      - "!auth/authconnect/**"
      - "!auth/authredis/**"
      - "!auth/examples/**"

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/deploy-go-module.yml
    with:
      module_path: auth
      bump_type: major
    secrets: inherit
