name: Release locking

on:
  push:
    branches:
      - main
    paths:
      - "locking/**"

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/deploy-go-module.yml
    with:
      module_path: locking
      bump_type: patch
    secrets: inherit
