name: Release connectutil

on:
  push:
    branches:
      - main
    paths:
      - "connectutil/**"

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/deploy-go-module.yml
    with:
      module_path: connectutil
      bump_type: patch
    secrets: inherit
